### PR TITLE
Remove 'features' and raise exception when using unsupported API

### LINKED ISSUE #206: Consider caching version comparisons or do them once in `__init__`
https://github.com/DCSBL/python-homewizard-energy/blob/0de2bffdcb23aef8bb86261e61cb3fe90834acf3/homewizard_energy/features.py#L38

versions

### PR DESCRIPTION
**Pull request by DCSBL**
This removes the need of `Feature` comparison, it just tries and raises `UnsupportedError` as before.

Fixes #206

### CODE REVIEW

**Comment by DCSBL** [comment]
@bdraco, can you take a quick look at this? This should resolve your issue.

**Comment by bdraco** [comment]
Seems like that should do it. I don't actually have a way to test this though since that profile came from a user I was helping diagnose a performance issue

**Comment by bdraco** [comment]
Thanks @DCSBL

**Comment by pimw1** [comment]
Thank you both.

**Pull request merged**
